services:
  bot:
    build: .
    environment:
      - BOT_DISCORD_TOKEN=${BOT_DISCORD_TOKEN}
      - BOT_DATA_DIRECTORY=/var/button/embedder
    volumes:
      - type: bind
        source: ${COMPOSE_HOST_BOT_DATA_DIRECTORY}
        target: /var/button/embedder